---
apiVersion: v1
kind: Secret
metadata:
  name: rwaltr-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/rwaltr/home-ops
  name: rwaltr
