---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: media
spec:
  ports:
  - name: "7878"
    port: 7878
    protocol: TCP
    targetPort: 7878
  selector:
    app: radarr
  type: ClusterIP
