radarr:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    repository: ghcr.io/k8s-at-home/radarr
    pullPolicy: IfNotPresent
    tag: v3.2.2.5080

  strategy:
    type: Recreate

  env:

  service:
    main:
      ports:
        http:
          port: 7878

  ingress:
    main:
      enabled: false

  persistence:
    config:
      enabled: true
      existingClaim: radarr-config
    media:
      enabled: true
      type: custom
      mountPath: /media
      volumeSpec:
        nfs:
          server: 10.10.0.8
          path: /tank/nas/library
    downloads:
      enabled: true
      type: custom
      readOnly: true
      mountPath: /downloads
      volumeSpec:
        nfs:
          server: 10.10.0.8
          path: /tank/nas/library/downloads/completed

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000

  # Enable gathering Prometheus metrics
  # prometheus:
  #   podMonitor:
  #     enabled: false
  #     interval: 3m
  #     scrapeTimeout: 1m
  #     additionalLabels: {}

  # # When using the prometheus.podMonitor the following
  # # container is required
  # additionalContainers:
  # - name: exportarr
  #   image: ghcr.io/onedr0p/exportarr:v0.6.0
  #   imagePullPolicy: IfNotPresent
  #   args: ["exportarr", "radarr"]
  #   env:
  #   - name: PORT
  #     value: "32123"
  #   - name: URL
  #     value: "http://localhost"
  #   - name: CONFIG
  #     value: "/config/config.xml"
  #   ports:
  #   - name: exportarr
  #     containerPort: 32123
  #   volumeMounts:
  #   - name: config
  #     mountPath: /config
  #     readOnly: true
