radarr:
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#
  
  image:
    repository: ghcr.io/k8s-at-home/radarr
    pullPolicy: IfNotPresent
    tag: v3.0.2.4552
  
  strategy:
    type: Recreate
  
  env:
    PUID: 1000
    GUID: 1000
  
  service:
    port:
      port: 7878
  
  ingress:
    enabled: false
    
  persistence:
    config:
      enabled: true
      emptyDir:
        enabled: false
      existingClaim: radarr-config

  additionalVolumes:
    - name: media
      nfs:
        server: 10.10.0.8
        path: /tank/nas/library
    - name: downloads
      nfs:
        server: 10.10.0.8
        path: /tank/nas/library/downloads/completed

  additionalVolumeMounts:
    - name: media
      mountPath: /media
      readOnly: true
    - name: downloads
      mountPath: /downloads
      readOnly: true

  # Enable gathering Prometheus metrics
  # prometheus:
  #   podMonitor:
  #     enabled: false
  #     interval: 3m
  #     scrapeTimeout: 1m
  #     additionalLabels: {}
  
  # # When using the prometheus.podMonitor the following
  # # container is required
  # additionalContainers:
  # - name: exportarr
  #   image: ghcr.io/onedr0p/exportarr:v0.6.0
  #   imagePullPolicy: IfNotPresent
  #   args: ["exportarr", "radarr"]
  #   env:
  #   - name: PORT
  #     value: "32123"
  #   - name: URL
  #     value: "http://localhost"
  #   - name: CONFIG
  #     value: "/config/config.xml"
  #   ports:
  #   - name: exportarr
  #     containerPort: 32123
  #   volumeMounts:
  #   - name: config
  #     mountPath: /config
  #     readOnly: true