---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: recyclarr-secret
    template:
      data:
        SONARR_API_KEY: "{{ .sonarr }}"
        RADARR_API_KEY: "{{ .radarr }}"
  dataFrom:
    - extract:
        key: arr
