sonarr:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #
  
  image:
    repository: ghcr.io/k8s-at-home/sonarr
    pullPolicy: IfNotPresent
    tag: v3.0.6.1196
  
  strategy:
    type: Recreate
  
  env:
  
  service:
    port:
      port: 8989
  
  ingress:
    enabled: false
  
  
  persistence:
    config:
      enabled: true
      emptyDir:
        enabled: false
      existingClaim: sonarr-config
  
  additionalVolumes:
    - name: media
      nfs:
        server: 10.10.0.8
        path: /tank/nas/library
    - name: downloads
      nfs:
        server: 10.10.0.8
        path: /tank/nas/library/downloads/completed

  additionalVolumeMounts:
    - name: media
      mountPath: /media
      readOnly: true
    - name: downloads
      mountPath: /downloads
      readOnly: true

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000



