# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: shlink-web
  namespace: default
stringData:
  SHLINK_SERVER_API_KEY: ENC[AES256_GCM,data:WpcdAGJgqy5W6kJpA3cpdszJJ1HPLdMwDDwUAxdurtJSNCcd,iv:cKn9N8LzJHZH4OX+lE16SUo5RxnigO/NJ6KXaj1tmWk=,tag:YtWuQbTy47ycrg0gCoF5Jg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age189npag0lz2hl425ldurk8czrpyv69tg4cgqgzl7wjh60w39sysesazu4u6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSjY1d1pjWGdwQkJ4L2RP
        S0lNM0xFNlRFdW5OTzBpQ3dJWGdJM2NPbUhvCjZPeFQ4S0VISmxZZUp4WklYd2Jq
        a3dKRllPUmkvMGx1MG1rNjZ2M0FYTUUKLS0tIHpFZC92UTNvMUwxR29OWEJQZzBv
        b3IxY1RIbDlQMStXTUc1R2VVVk84NkUKXP4hoFAbYq5hSgd6RD/UCDGsS26k4yjn
        l6e5E4KSPZwZBV6TzKVsKj85GdlQCFxR15gawVaZxyIQ+5LwAxJT+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-11-08T03:06:47Z"
  mac: ENC[AES256_GCM,data:69VePKeJB+A4tQX3K8onqgJyKin5cXQ3UsCGULzXC56nZTnn1za9a9hn09qWx7JuogsiNucWlDvCZW8WrnUsLTfozfkU6BRjv5a2yvtXjUdpnXZRKAeJ7idkogD4eU6zUJq/swUiIpzT1ZCiTVZn4bUaBMHoiY1bd+91jcIdX24=,iv:+LoD88AC0vdDEvfdPnwn8f0Ebdu0q0IyLgpoeyXbvug=,tag:hWIeFwENw8IaNyBKCLXhCw==,type:str]
  pgp:
    - created_at: "2022-11-08T03:06:46Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQEMA1nCbZ66Iz0yAQf9HKcmXRqxAOdvnfSQZYLQOPFSYtbpIFAND2Zpd+Rtu9Lz
        lEMdLRxkZbrhKqIRVOU1NKc2NB74QYc4352C8Sd5SeybGwf1VS6bSWtO8HTdvfHl
        3kOjpsetXhhvpWEvQEphIqpEiOyg13d7G9Fe4w/KRokX/SEBQmlzx3X2Z5GU3aEu
        /olEXS7rUy2vFQP+4JyP3VXpXo2hcn0JVj2yIABwD86EpBwtx8WGmDZQGBb5Xsqa
        p39unzL6jEmhro8nSudB6S+LAEM3wg9ctqRIsgmLPjlAAf/1Ot3k/2mi06l7g+XN
        G6QIVwhtCWbVqTGw3WIDPoFg3d1A/Zehr1ndVu9/p9RmAQkCEOmktO5FbqzH3LVd
        wV6/7ReqIAiA7gp0k2eMel03R8KBjkFs6py9hP/iXq8NXKeXrEGdfm0xDymMMMoH
        ttF7h4oQhg+h9pbMJyasEfNZEymTAAVrydYXVWl9L+mDravqhcdd
        =MC3a
        -----END PGP MESSAGE-----
      fp: 4186BF653F777F6190DAF3C469977470B0541C75
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
