name: external-dns
apiVersion: v2
version: 1.0.0
dependencies:
  - name: external-dns
    version: 1.9.0
    repository: https://kubernetes-sigs.github.io/external-dns/
  - name: addons
    version: 1.0.0
    repository: file://../../../charts/addons
