external-dns:
  fullnameOverride: external-dns

  image:
    registry: docker.io
    repository: k8s.gcr.io/external-dns/external-dns
    tag: v0.11.0

  sources:
    - crd
    - service
    - ingress
  provider: cloudflare

  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-token
          key: CF_API_TOKEN
          optional: false

  interval: "1m"
  replicas: 1

  crd:
    create: true
  domainFilters:
    - "waltr.tech"
    - "blackphidora.com"
    - "rwaltr.pro"
