external-dns:
  fullnameOverride: external-dns

  image:
    registry: docker.io
    repository: bitnami/external-dns
    # renovatebot:alturl=https://github.com/bitnami/bitnami-docker-external-dns
    tag: 0.11.1-debian-10-r9

  sources:
    - crd
    - service
    - ingress
  provider: cloudflare

  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare_token
          key: CF_API_TOKEN
          optional: false

  interval: "1m"
  replicas: 1

  crd:
    create: true
  domainFilters:
    - "waltr.tech"
    - "blackphidora.com"
    - "rwaltr.pro"
