---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarr
  name: sonarr
  namespace: media
spec:
  ports:
  - name: "8989"
    port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app: sonarr
  type: ClusterIP
