---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: leonvtt-data
  namespace: jgleon
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: nfs-client
