---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: core
  path: ./k8s/kyz/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: rwaltr-homeops
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
  # postBuild:
  #   substituteFrom:
  #     - kind: ConfigMap
  #       name: cluster-settings
  #     - kind: Secret
  # name: cluster-secrets
