---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: charts
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/kyz/charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: rwaltr-homeops
