---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/kyz/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: rwaltr-homeops
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
