---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: charts
    - name: config
    - name: crds
  path: ./k8s/kyz/core
  prune: false
  sourceRef:
    kind: GitRepository
    name: rwaltr-homeops
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      # - kind: Secret
      #   name: cluster-secrets
