apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-prod
spec:
  acme:
    email: ryan@blackphidora.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-prod
    solvers:
      - dns01:
          cloudflare:
            email: ryan@blackphidora.com
            apiTokenSecretRef:
              name: cloudflareapikey
              key: API_KEY
