# yamllint disable
---
apiVersion: v1
kind: Service
metadata:
  name: deluge
  namespace: media
  labels:
    app.kubernetes.io/name: deluge
    app.kubernetes.io/instance: deluge
    app.kubernetes.io/version: "v2.0.3-2201906121747"
spec:
  type: ClusterIP
  externalIPs:
    - 172.30.0.23
  ports:
    - port: 8112
      targetPort: http
      protocol: TCP
      name: http
    - port: 53442
      targetPort: torrent
      protocol: TCP
      name: torrent
  selector:
    app.kubernetes.io/name: deluge
    app.kubernetes.io/instance: deluge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  namespace: media
  labels:
    app.kubernetes.io/name: deluge
    app.kubernetes.io/instance: deluge
    app.kubernetes.io/version: "v2.0.3-2201906121747"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: deluge
      app.kubernetes.io/instance: deluge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deluge
        app.kubernetes.io/instance: deluge
    spec:
      serviceAccountName: default
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: deluge
          image: "linuxserver/deluge:version-2.0.3-2201906121747ubuntu18.04.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8112
              protocol: TCP
            - name: torrent
              containerPort: 53442
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: downloads
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: deluge-config
        - name: downloads
          nfs:
            path: /tank/nas/library/downloads
            server: 10.10.0.8
