---
gonic:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml

  image:
    # -- image repository
    repository: sentriz/gonic
    # -- image pull policy
    pullPolicy: IfNotPresent
    # -- image tag
    tag: v0.13.1

  # -- environment variables. See more environment variables in the [gonic documentation](https://github.com/sentriz/gonic#configuration-options)
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: America/Chicago
    GONIC_MUSIC_PATH: /music
    GONIC_PODCAST_PATH: /podcast
    GONIC_CACHE_PATH: /cache

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 80

  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: '10'
        cert-manager.io/cluster-issuer: le-prod
      hosts:
      - host: gonic.waltr.tech
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: gonic-waltr-tech
        hosts:
        - gonic.waltr.tech

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    data:
      enabled: true
      mountPath: /data
      type: pvc
      size: 1Gi
      accessMode: ReadWriteOnce
    podcasts:
      enabled: true
      readOnly: true
      mountPath: /podcast
      type: custom
      volumeSpec:
        nfs:
          server: 10.10.0.8
          path: /tank/nas/library/podcasts
    cache:
      enabled: true
      type: emptyDir
      mountPath: /cache
    music:
      enabled: true
      readOnly: true
      mountPath: /music
      type: custom
      volumeSpec:
        nfs:
          server: 10.10.0.8
          path: /tank/nas/library/music
