---
creation_rules:
  - pgp: >-
      4186BF653F777F6190DAF3C469977470B0541C75
    age: >-
      age189npag0lz2hl425ldurk8czrpyv69tg4cgqgzl7wjh60w39sysesazu4u6
  # - hc_vault_transit_uri: "https://vault.waltr.tech/v1/sops/keysage189npag0lz2hl425ldurk8czrpyv69tg4cgqgzl7wjh60w39sysesazu4u6/mainkey"
