---
creation_rules:
  - path_regex: k8s/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age189npag0lz2hl425ldurk8czrpyv69tg4cgqgzl7wjh60w39sysesazu4u6
        pgp:
          - 4186BF653F777F6190DAF3C469977470B0541C75
  - pgp: >-
      4186BF653F777F6190DAF3C469977470B0541C75
    age: >-
      age189npag0lz2hl425ldurk8czrpyv69tg4cgqgzl7wjh60w39sysesazu4u6
