---
creation_rules:
  - encrypted_regex: "((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))"
    age: >-
      age189npag0lz2hl425ldurk8czrpyv69tg4cgqgzl7wjh60w39sysesazu4u6
    pgp: "43A697C7D3B8377EB8A0E7C127DDBC18CC4F3E04"
    # hc_vault_transit_uri: "https://vault.waltr.tech/v1/sops/keys/mainkey"
