#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: pe46dro/xbackbone-docker
  pullPolicy: IfNotPresent
  tag: 3.3.3

strategy:
  type: Recreate

env: {}
  # TZ: UTC
  # LOG_LEVEL: info

service:
  port:
    port: 80


ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: le-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
  hosts:
    - host: images.waltr.tech
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - images.waltr.tech
      secretName: imageswaltrtech-cert

persistence:
  config:
    enabled: true
    mountPath: /app/config
