haste-server:
  image:
    repository: ghcr.io/k8s-at-home/haste-server
    pullPolicy: IfNotPresent
    tag: latest
  env:
    HOST: 0.0.0.0
    PORT: "7777"
    KEY_LENGTH: "10"
    MAX_LENGTH: "4000000"
    STATIC_MAX_AGE: "86400"
    RECOMPRESS_STATIC_ASSETS: "true"
    KEYGENERATOR_TYPE: phonetic
    DOCUMENTS: about=./about.md
    LOGGING_LEVEL: verbose
    LOGGING_TYPE: Console
    LOGGING_COLORIZE: "true"
    RATELIMITS_NORMAL_TOTAL_REQUESTS: "500"
    RATELIMITS_NORMAL_EVERY_MILLISECONDS: "60000"
    RATELIMITS_WHITELIST: ""
    RATELIMITS_BLACKLIST: ""
    STORAGE_EXPIRE_SECONDS: "604800"

  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-prod
      hosts:
        - host: bin.waltr.tech
          paths:
            - path: /
      tls:
        - secretName: bin-waltr-tech
          hosts:
            - bin.waltr.tech

  persistence:
    config:
      enabled: true
      type: emptyDir
