owncloud-ocis:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  strategy:
    type: Recreate

  env:
    TZ: America/Chicago

  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-prod
      hosts:
        - host: "files.waltr.tech"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: files-waltr-tech
          hosts:
            - files.waltr.tech

    persistence:
      config:
        enabled: true
        mountpath: /config
