---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aqua-charts.yaml
  - bitnami-charts.yaml
  - bjw-s-charts.yaml
  - cloudnative-pg-charts.yaml
  - csi-driver-nfs-charts.yaml
  - descheduler-charts.yaml
  - emqx-charts.yaml
  - external-dns-charts.yaml
  - fairwinds-charts.yaml
  - gitea-charts.yaml
  - grafana-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - kyverno-charts.yaml
  - metrics-server-charts.yaml
  - node-feature-discovery-charts.yaml
  - project-calico-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - stakater-charts.yaml
  - vector-charts.yaml
