---
apiVersion: v1
kind: Service
metadata:
  name: rtorrent
  namespace: media
  labels:
    app: rtorrent
spec:
  ports:
  - port: 9080
    targetPort: 9080
    protocol: TCP
    name: web
  - port: 53442
    targetPort: 53442
    protocol: TCP
    name: seed
  selector:
    app: rtorrent
  externalIPs:
    - "172.30.0.23"
