#!/usr/bin/env bash
#MISE description="Build and switch to new NixOS configuration (requires sudo)"
#MISE arg "[host]" help="Host to switch (default: mouse)"

HOST="${1:-mouse}"
sudo nixos-rebuild switch --flake ".#$HOST"
