#image: 
#  name: traefik
#  tag: 2.4.8

service:
  externalIPs: 
    - 172.30.0.10

additionalArguments:
  - "--api.insecure=true"
  - "--accesslog=true"
  - "--log.level=INFO"
  #- "--providers.kubernetesingress.ingressclass=traefik"
  - "--providers.kubernetesingress.ingressendpoint.hostname=traefik.home.waltr.tech"
  - "--serverstransport.insecureskipverify=true"
  - "--entryPoints.websecure.http.tls=true"
env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare
        key: dns-token

ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true
  fallbackApiVersion: v1

logs:
  general:
    level: INFO

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true