apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rwaltr
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "https://github.com/rwaltr/infra"
