---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  # TODO: create grafanadashboard.yaml and re-enable
  # - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  # TODO: create and re-enable
  # - ./httproute.yaml
  # TODO: create and re-enable
  # - ./podmonitor.yaml
  # TODO: create and re-enable
  # - ./prometheusrule.yaml
  # TODO: create and re-enable
  # - ./receiver.yaml
