---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: sonarr
  namespace: default
spec:
  repository:
    kind: ClusterRepository
    name: cluster-kopia
  sources:
    - pvc:
        name: sonarr-config
      sourcePathStrategy: PvcName
  copyMethod: Direct
  mover:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    podSecurityContext:
      fsGroup: 1000
  retention:
    keepLatest: 7
    keepDaily: 14
    keepWeekly: 4
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotschedule_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: sonarr-nightly
  namespace: default
spec:
  policyRef:
    name: sonarr
  schedule:
    cron: "H 7 * * *"
    jitter: 30m
    runOnCreate: false
