jellyfin:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    repository: jellyfin/jellyfin
    pullPolicy: IfNotPresent
    tag: 10.7.5

  strategy:
    type: Recreate

  env:
    TZ: America/Chicago

  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-prod
      hosts:
        - host: "jellyfin.waltr.tech"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jellyfin-waltr-tech
          hosts:
            - jellyfin.waltr.tech


  persistence:
    config:
      enabled: true
      existingClaim: jellyfin-config
    # Cache does NOT contain temporary transcoding data.
    cache:
      enabled: true
      mountPath: /cache
      accessMode: ReadWriteOnce
      type: pvc
      size: 1G
    media:
      enabled: true
      type: custom
      mountPath: /media
      readOnly: true
      volumeSpec:
        nfs:
          server: 10.10.0.8
          path: /tank/nas/library
    transcode:
      enabled: true
      type: emptyDir
      mountPath: /config/transcodes
