#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: organizr/organizr
  pullPolicy: Always
  tag: latest

strategy:
  type: Recreate

env:
  # TZ: UTC
  # PUID: 1000
  # PGID: 1000

service:
  port:
    port: 80

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: le-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://raw.githubusercontent.com/causefx/Organizr/v2-develop/plugins/images/organizr/logo-wide.png"

  hosts:
    - host: organizr.waltr.tech
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - organizr.waltr.tech
      secretName: organizrwaltrtech-cert

persistence:
  config:
    enabled: true
    emptyDir:
      enabled: false
