---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jackett
  name: jackett
  namespace: media
spec:
  ports:
  - name: "9117"
    port: 9117
    protocol: TCP
    targetPort: 9117
  selector:
    app: jackett
  type: ClusterIP
