#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: linuxserver/booksonic-air
  pullPolicy: IfNotPresent
  tag: v2009.1.0-ls2

strategy:
  type: Recreate

env:
  # TZ: UTC
  PUID: "1000"
  PGID: "1000"
  # CONTEXT_PATH=url-base # Used to set the base path for reverse proxies eg. /booksonic, /books, etc.

service:
  port:
    port: 4040

ingress:
  #enabled: true
  annotations:
    cert-manger.io/cluster-issuer: le-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: booksonic.waltr.tech
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - booksonic.waltr.tech
      secretName: booksonicwaltrtech-cert  


persistence:
  config:
    enabled: true
    emptyDir: false

additionalVolumeMounts:
  - name: audiobooks
    mountPath: /audiobooks
  - name: podcasts
    mountPath: podcasts
    
additionalVolumes:
  - name: audiobooks
    nfs:
      path: /tank/nas/library/audiobooks
      server: 10.10.0.8
  - name: podcasts
    nfs:
      path: /tank/nas/library/audiobooks
      server: 10.10.0.8