---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./kopia.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: zigbee2mqtt-config
    files:
      - configuration.yaml=./configuration-z2m.yaml
generatorOptions:
  disableNameSuffixHash: true