---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-dns
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-secret
            key: CF_API_TOKEN
    sources:
      - gateway-httproute
    policy: sync
    registry: txt
    txtOwnerId: kyz
    domainFilters:
      - kyz.rwalt.pro
    triggerLoopOnEvent: true
    serviceMonitor:
      enabled: true
    logLevel: debug
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-secret
