vault:

  server:
    image:
      repository: "vault"
      tag: "1.7.3"
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-prod
      hosts:
        - host: vault.waltr.tech
          paths: [/]
      tls:
        - hosts: [vault.waltr.tech]
          secretName: vault-waltr-tech
  dataStorage:
    storageClass: nfs-client
  ui:
    enabled: true
  csi:
    enabled: true
  injector: 
    enabled: true