ombi:
  env: {}

  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-prod
      hosts:
        - host: "ombi.waltr.tech"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ombi-waltr-tech
          hosts:
            - ombi.waltr.tech

  persistence:
    config:
      enabled: true
