---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
spec:
  chartRef:
    kind: OCIRepository
    name: searxng
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      searxng:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: docker.io/searxng/searxng
              tag: 2026.9.19-367fb6537@sha256:5b39c7df0647ef73b0ca56d478026015c92bb4150f9f03ed9e1250fba6e1da99
            env:
              SEARXNG_BASE_URL: https://search.waltr.tech
              TZ: America/Chicago
            envFrom:
              - secretRef:
                  name: searxng-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETGID
                  - SETUID
                  - DAC_OVERRIDE
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: searxng
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - search.waltr.tech
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: searxng
                port: *port
    persistence:
      config:
        type: configMap
        name: searxng-config
        globalMounts:
          - path: /etc/searxng/settings.yml
            subPath: settings.yml
            readOnly: true
      run:
        type: emptyDir
        globalMounts:
          - path: /etc/searxng
      cache:
        type: emptyDir
        globalMounts:
          - path: /var/cache/searxng
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    configMaps:
      searxng-config:
        forceRename: searxng-config
        data:
          settings.yml: |
            use_default_settings: true

            server:
              limiter: false
              image_proxy: true
              method: GET
              public_instance: false

            search:
              formats:
                - html
                - json
              autocomplete: duckduckgo
              favicon_resolver: duckduckgo
              languages:
                - all
                - en
                - en-US

            general:
              instance_name: SearXNG

            ui:
              default_theme: simple
              infinite_scroll: true
              query_in_title: true
              results_on_new_tab: true
              static_use_hash: true
              theme_args:
                simple_style: auto

            categories_as_tabs:
              general:
              images:
              videos:
              map:

            enabled_plugins:
              - Basic Calculator
              - Hash plugin
              - Open Access DOI rewrite
              - Self Informations
              - Tracker URL remover
              - Unit converter plugin
