keyid: ENC[AES256_GCM,data:sWUfNoBFJRqTRdfoVgA4ZmLxdxKV3zrYsw==,iv:NOa1BWgnmHZF++81RQVKRwquR/oRJmEfKjJIbBSOQtY=,tag:VOtfW9vFNPzd29ksjJcVuQ==,type:str]
keyName: ENC[AES256_GCM,data:YOZt67zrlLmhzYh6X484HBjX,iv:bEBY+W+BdmMrKOwkEMSV4IIIv1AO2UhdTHli4OAhtcQ=,tag:8it5Hk/JpI4cHQUjdFzoQA==,type:str]
applicationKey: ENC[AES256_GCM,data:ZYvrhM9IW8gih51Dg7LOupYFyeAPjeQ5yf+gUJ4Daw==,iv:BWNzNV1zv6ljIgeX88cI8/K3UVeu2wQKXrX9cWFeGtA=,tag:+G/JJ6vrLjQoBBBlBLePIg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age189npag0lz2hl425ldurk8czrpyv69tg4cgqgzl7wjh60w39sysesazu4u6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNnpRVmtacVlaREYweFZz
        NXU5T2dhNDJjczc4bGsyZm5ZekdaWVJySXpBCi9rYk0ycXdCL2FtTkNCdHhJaE5r
        TEdrNmFENjlyd3B3SHFRdzNuSGtIb1EKLS0tIGZSQ0ZncG5XM0h5S21jVFVoK2JU
        UTJvOFdvUlNRcExPdmVDYUZtOHlMMk0KHVR0TYVAKxBxMuOFB/X8c3dWmEOmuppw
        8FV5LN81AQ0Nbg4CgscPjzpo8BRJz1zdu9FQHIo5xrk8T1NaF1tfuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-02-23T02:49:26Z"
  mac: ENC[AES256_GCM,data:EnDpvPjruYeQV1CyFQfPbsjLKwablWcQjzs6+B1hFtQu8vyjbEast8jVDZPV/lbIHMdDGLSjrS2s3MmTaCqV+JulVsYkXZpEOB7Rw2ZziwNine6/jWydFAXjl6Pb6BElYw5K4d//vM7U5EL84u12bppPgXTEgWz3KFsW8m3P5SI=,iv:TOBQaT/7SpJxAPeLjuPiaxhyFZU+3gSv7NjTafppTtE=,tag:7PSAPMIz9UhxByqc1aYSmA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3
