# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:2Dw3FmpFUCt6iCYFpw==,iv:S3A8jibMLVCQfdw15qn5vCphNUkBzI4NUMhb1dk9+JQ=,tag:iOZbuTdNd355Rnscul8w4w==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - hc_vault: []
          age:
            - recipient: age189npag0lz2hl425ldurk8czrpyv69tg4cgqgzl7wjh60w39sysesazu4u6
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ2JMazc0ZiswZXBuRnRw
                ZXdNK2QybFpSSXVQS3JnQjIzUzFIRXI0Z0JZCklBUGovYnlteUpnRU9OZnBaTWdv
                eUMrVktyelJ3ZEZQTk1obVphaVhUeUUKLS0tIHN1eWJMZWJsU0pFVmlYK3Babi9W
                NTliWlI3aDJrOUV5dUwvK0VsYi8zNWsKRzgne+zk5L7zDHLwFZ4rpPFH9aPNz5IG
                5VJ1gs9av5nKO4rftoo4CP2M1LJt0JZCSBH6/TBvRvisFMmPXjsCCyY=
                -----END AGE ENCRYPTED FILE-----
        - pgp:
            - created_at: "2022-09-26T01:09:19Z"
              enc: |
                -----BEGIN PGP MESSAGE-----

                hQEMA1nCbZ66Iz0yAQgAgfnB62CyRVkHwoiG9h+viIbVfSbC6GG/Au2emlRpMNMz
                YXLJLuY3JyhrW3P3/iRm6VYuJc9Ly3QeCpMoIzXuYU3nOLihFauJSHzSliydoAHq
                s9w+R3nURo9rcsqMHGj0ow5xmOcOJWzw+U/K+JYxSlnESG7dkfxEfaywXxII9qpQ
                vNBnQmjXIMszzv4OBIe5cphgBCDk6XtLD1dIifpJ++2xN5pk6hkz+VhfB0QXesAj
                64eDFQbsrSNFp6FNpET/JA9TiGW2TlgLI3unkiS9/YjLID2TNesBNm9MXi469xgM
                EqjkFkQWowO0Qa0RuqSJjLlagulOSc52Tlv2g9XvqNRnAQkCEFlmUM5BxODU3AkZ
                GxH9QP7SVqx+Qn1AmTT+9YyIx6ea2bH6ympq9km+ROYozG9wNNoYE633/5SiRGOY
                jk69u8gnhPBL3a57VoOtK3Oip2N1QUqwW7xAeFT4kGOrHe4a8cwORg==
                =275Z
                -----END PGP MESSAGE-----
              fp: 4186BF653F777F6190DAF3C469977470B0541C75
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-26T01:09:20Z"
    mac: ENC[AES256_GCM,data:Oq+8sSRk9LoKGFDtHcR2jlH1WtM/hxUQxuAdV0EVD9wh6FrRPeiK9111XiAM7zcwi0SGYTsLx+KiqO8rwf9WExpYRcupEiN0htzskdw6+P55OD+riKCXnm5AiZx0tG5v9aoNbznxvCd2OsYcgY76ALzGSHlaxc+7E0P9sbc8RzE=,iv:8t4UQ93+Hob4tIQjbJravZv9uXCQN3Gr2YOskwNsPGk=,tag:LTuOmPwCucjwIIRvMOG2gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
