---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zigbee2mqtt
spec:
  components:
    - ../../../../components/kopiur/backup
  interval: 1h
  path: ./infra/k8s/kyz/apps/default/zigbee2mqtt/app
  postBuild:
    substitute:
      APP: zigbee2mqtt
      PVC: zigbee2mqtt
      KOPIUR_CRON: "H 4 * * *"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  dependsOn:
    - name: openebs
      namespace: openebs
    - name: mosquitto
  wait: false
