jackett:

  image:
    repository: ghcr.io/k8s-at-home/jackett
    pullPolicy: IfNotPresent
    tag: v0.18.205
  
  strategy:
    type: Recreate
  
  env: {}
    # TZ: UTC
  
  service:
    port:
      port: 9117
  
  ingress:
    enabled: false
  
  persistence:
    config:
      enabled: true
      existingClaim: jackett-config
  
    torrentblackhole:
      enabled: false
      emptyDir:
        enabled: false
      mountPath: /downloads
      ## Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      # storageClass: "-"
      # accessMode: ReadWriteOnce
      # size: 1Gi
      ## Do not delete the pvc upon helm uninstall
      # skipuninstall: false
      # existingClaim: ""
  