jackett:
  image:
    repository: ghcr.io/k8s-at-home/jackett
    pullPolicy: IfNotPresent
    tag: v0.19.68

  strategy:
    type: Recreate

  env:
    TZ: America/Chicago

  ingress:
    main:
      enabled: false

  persistence:
    config:
      enabled: true
      existingClaim: jackett-config
