---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: rwaltr-homeops
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/rwaltr/home-ops.git
  ref:
    branch: fluxify
  # secretRef:
  # name: github-deploy-key
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/kyz/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: rwaltr-homeops
