foundryvtt:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    repository: felddy/foundryvtt
    pullPolicy: IfNotPresent
    tag: 0.8.6

  strategy:
    type: Recreate
  # See more environment variables in the foundryvtt documentation
  # https://github.com/felddy/foundryvtt-docker#environment-variables

  env:
    FOUNDRY_HOSTNAME: "jgleon.vtt.waltr.tech"
    # TZ:

  envFrom:
    - secretRef:
        name: leonvtt-secret

  service:
    main:
      nameOveride: jgleon
      ports:
        http:
          port: 30000


  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-prod
      hosts:
        - host: "jgleon.vtt.waltr.tech"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jgleon-vtt-waltr-tech
          hosts:
            - jgleon.vtt.waltr.tech


  # Founderyvtt is hardcoded to use /data for its persistance for config and
  persistence:
    data:
      enabled: true
      mountPath: /data
      size: 10G
      accessMode: ReadWriteOnce
