global:
  domainName: "leon.vtt.waltr.tech"
foundryvtt:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    repository: felddy/foundryvtt
    pullPolicy: IfNotPresent
    tag: 9.245.0

  strategy:
    type: Recreate
  # See more environment variables in the foundryvtt documentation
  # https://github.com/felddy/foundryvtt-docker#environment-variables

  env:
    FOUNDRY_HOSTNAME: "jgleon.vtt.waltr.tech"
    # TZ:

  envFrom:
    - secretRef:
        name: leonvtt-secret

  service:
    port:
      port: 30000

  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: "gamepad"
      hosts:
        - host: "{{ .Values.global.domainName }}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts: ["{{ .Values.global.domainName }}"]
          secretName: '{{ .Values.global.domainName | replace "." "-" }}' # Founderyvtt is hardcoded to use /data for its persistance for config and

  persistence:
    data:
      enabled: true
      emptyDir:
        enabled: false
      mountPath: /data
      size: 10G
      accessMode: ReadWriteOnce
