---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "waltrtech-default"
  namespace: default
spec:
  secretName: "waltrtech-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "waltr.tech"
  dnsNames:
    - "waltr.tech"
    - "*.waltr.tech"
