apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bots
  name: auto-voice-channel
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
