
# Default values for deluge.

image:
  repository: linuxserver/deluge
  pullPolicy: IfNotPresent
  tag: version-2.0.3-2201906121747ubuntu18.04.1

strategy:
  type: Recreate

service:
  port:
    port: 8112
    port: 53442
  externalIPs:
    - 172.30.0.23

persistence:
  config:
    enabled: true
    emptyDir: false
    mountPath: /config
    storageClass: nfs-client

  downloads:
    enabled: false
    emptyDir: false
    mountPath: /downloads
    #storageClass: nfs-client
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    #accessMode: ReadWriteOnce
    #size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    # existingClaim: ""
additionalVolumeMounts: 
  - name: downloads
    mountPath: /downloads
additionalVolumes:
  - name: downloads
    nfs:
      server: 10.10.0.8
      path: /tank/nas/library/downloads

env: {}
  ## Optional ENV Vars that can be set.
  ## All values below are the current default values.
  # PUID: "1000"
  # PGID: "1000"
  # TZ: "Europe/London"
  # UMASK_SET: "022"
  # DELUGE_LOGLEVEL: "error"

addons:

  # Enable running a VPN in the pod to route traffic through a VPN
  vpn:
    enabled: false
