---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app minio
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2022-09-25T15-44-53Z
    env:
      TZ: "America/Chicago"
      MINIO_UPDATE: "off"
      MINIO_BROWSER_REDIRECT_URL: "https://minio.waltr.tech"
      MINIO_SERVER_URL: "https://s3.waltr.tech"
    envFrom:
      - secretRef:
          name: *app
    args: ["server", "/data", "--console-address", ":9001"]
    service:
      main:
        enabled: true
        ports:
          http:
            port: &port-console 9001
          api:
            enabled: true
            port: &port-api 9000
        monitor:
          enabled: false
          # endpoints:
          #   - port: api
          #     scheme: http
          #     path: /minio/v2/metrics/cluster
          #     interval: 1m
          #     scrapeTimeout: 10s
          #     bearerTokenSecret:
          #       name: minio-prometheus
          #       key: token
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &host-console "{{ .Release.Name }}.waltr.tech"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port-console
          - host: &host-api "s3.waltr.tech"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port-api
        tls:
          - hosts:
              - *host-console
              - *host-api
    # podSecurityContext:
    #   runAsUser: 568
    #   runAsGroup: 568
    #   fsGroup: 568
    #   fsGroupChangePolicy: "OnRootMismatch"
    #   supplementalGroups:
    #     - 100
    persistence:
      config:
        enabled: true
        type: nfs
        server: 10.10.0.8
        path: /tank/nas/s3
        readOnly: false
        mountPath: /data
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
