apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: minecraft
spec:
  endpoints:
  - dnsName: gt.mc.waltr.tech
    recordTTL: 180
    recordType: CNAME
    targets:
      - home.waltr.tech
