---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./apps/cert-manager
  - ./apps/external-secrets
  - ./apps/flux-system
  - ./apps/kopiur-system
  - ./apps/kube-system
  - ./apps/network
  - ./apps/o11y
  - ./apps/openebs
