cloudflare_email: ENC[AES256_GCM,data:FPYEGJyTuVxH8sX2xu+FJQ==,iv:k/pb+zbx1VfjXAXnGfKDqyk1C0D1wYVr/pRy1L71U+w=,tag:+B+djK3BM5p5VKWpeCEWkw==,type:str]
cloudflare_api_key: ENC[AES256_GCM,data:+yGTNXL+JyUIzXeJ2l21PX7c/fJqZUcnVy+lA32xUoeKgCrV8w==,iv:KOjng05HnNQUUFql8UOT0YeGyNTZPmkxs+lWQ+Uvb20=,tag:D1mMwdT4hCG6fd8B4NBr2g==,type:str]
cloudflare_oldfamily: ENC[AES256_GCM,data:2JwIhz7F3ZT7hRpQ,iv:4zMmouNsWjEtz0PkeEv01o1Mdmrw5eMCybQ9HTiO4JU=,tag:U4MH/CyC8wco+S8iGtA6bg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age189npag0lz2hl425ldurk8czrpyv69tg4cgqgzl7wjh60w39sysesazu4u6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cys2TjYwek9zdWV3V09s
        Z2pyL0VWOW9kcDNhODNoakpOZ2ZLMEsrQ1dZCngreVRPeUdZU1dRd09MY1ZJcjN1
        OGRCWlU4RllHdURSRTBZTzJGZ28vU0EKLS0tIG5CWjY4c09tSkdQNVpvZEVDSVJL
        TGp4bU5RL0lwQlpXRnc0V0VWTUdjdG8KRWv0opGpP/mUxvE8LI9URXspPHGGPbdu
        UUzNCH8YCI+iU6WVNy6hVIuviWKyJwod5FX3xRmgb3BZkpER80nFAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-10-29T22:46:53Z"
  mac: ENC[AES256_GCM,data:3lVgi5NPTYHsPe0uNw2lt0iiIQiS8sV4BNKQ2zfZ14Xzu5wouXgOZ1mt9DUeg74OE72wuBma5KUx8PHWzNHV5uwHt8QhoPqRqcj0trS8ehETy2d7QLrhhnD5kGhvDy64Qqo7+WK8uIV/mwMj78abuPH9Wp+s2xa+Vsj+2vTUpt0=,iv:C+KyT4D2oSrZNJBxrk8VYqw5X3ZFSrDXVwBXVincqeg=,tag:IWUBP+nmDGrkOPinzb9teg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3
