apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: kyz-0
  user: admin
spec:
  hosts:
  - ssh:
      address: 192.168.88.232
      user: rwaltr
      port: 22
      keyPath: null
    role: controller+worker
  options:
    wait:
      enabled: true
    drain:
      enabled: true
      gracePeriod: 2m0s
      timeout: 5m0s
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true
      podSelector: ""
      skipWaitForDeleteTimeout: 0s
    concurrency:
      limit: 30
      workerDisruptionPercent: 10
      uploads: 5
    evictTaint:
      enabled: false
      taint: k0sctl.k0sproject.io/evict=true
      effect: NoExecute
      controllerWorkers: false
