---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarr
  name: sonarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy: {}
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - image: ghcr.io/linuxserver/sonarr
        name: sonarr
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /media
            name: media
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: media
          nfs:
            server: 10.10.0.8
            path: /tank/nas/library
