---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: rtorrent-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
