nfs-subdir-external-provisioner:
  fullnameOverride: nfs-client-provisioner
  storageClass:
    defaultClass: true
    create: false
    name: nfs-client
    defaultClass: true

  nfs:
    server: storage2.waltr.lab
    path: /tank/k8s
