---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app navidrome
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/navidrome
      tag: 0.48.0@sha256:2ff33a7fd75521998683a4e50b490adfad9697c97edd2106b56f835547781de7
    env:
      TZ: "America/Chicago"
      ND_DATAFOLDER: /config
      ND_ENABLEGRAVATAR: "false"
      ND_LOGLEVEL: info
      ND_MUSICFOLDER: /music
      ND_PORT: &port 8080
      ND_PROMETHEUS_ENABLED: "true"
      # ND_REVERSEPROXYUSERHEADER: "Remote-User"
      # ND_REVERSEPROXYWHITELIST: "${NET_POD_CIDR}"
      ND_SCANSCHEDULE: "@every 1h"
    service:
      main:
        ports:
          http:
            port: *port
    serviceMonitor:
      main:
        enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          auth.home.arpa/enabled: "true"
          external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &host "navidrome.waltr.tech"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    volumeClaimTemplates:
    persistence:
      config:
        mountPath: /config
        type: pvc
        size: 5Gi
        enabled: true
      music:
        enabled: true
        type: nfs
        server: "10.10.0.8"
        path: /tank/nas/library/music
        mountPath: /music
        readOnly: true
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 750Mi
