---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ombi
  name: ombi
  namespace: media
spec:
  ports:
  - name: "3579"
    port: 3579
    protocol: TCP
    targetPort: 3579
  selector:
    app: ombi
  type: ClusterIP
