qbittorrent:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    repository: ghcr.io/k8s-at-home/qbittorrent
    pullPolicy: IfNotPresent
    tag: v4.3.4.1

  strategy:
    type: Recreate

  env:
    TZ: America/Chicago

  # service:
  #   port:
  #     port: 8080
  #   additionalServices:
  #   - enabled: true
  #     nameSuffix: bittorrent
  #     type: LoadBalancer
  #     externalTrafficPolicy: Local
  #     externalIPs:
  #         - 172.30.0.24
  #     port:
  #       port: 53443
  #       name: bittorrent
  #       protocol: TCP
  #       targetPort: 53443

  service:
    main:
      ports:
        http:
          port: 8080
    bittorrent:
      enabled: true
      type: LoadBalancer
      externalIPs:
        - 172.30.0.24
      ports:
        bittorrent:
          enabled: true
          port: 53443
          protocol: TCP
          targetPort: 53443

  settings:
    automaticPortSetup: true

  ingress:
    main:
      enabled: false

  persistence:
    config:
      enabled: true
    downloads:
      enabled: true
      type: custom
      volumeSpec:
        nfs:
          server: 10.10.0.8
          path: /tank/nas/library/downloads
