---
cilium:
  ipam:
    mode: kubernetes
  # k8sServiceHost: 10.10.0.9
  # k8sServicePort: 6443
  # kubeProxyReplacment: strict
  operator:
    replicas: 1
  bgp:
    enabled: true
    announce:
      loadbalancerIP: true
      podCIDR: true
  hubble:
    tls:
      auto:
        method: helm
