---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Download SSHCA
      get_url:
        url: https://vault.waltr.tech/v1/sshca/public_key
        dest: /etc/ssh/cakey.pem
      notify: Reload SSHD
    - name: Configure SSH for CA
      ansible.builtin.lineinfile:
        line: "TrustedUserCAKeys /etc/ssh/cakey.pem"
        path: /etc/ssh/sshd_config.d/cakey.conf
        create: yes
      notify: Reload SSHD

  handlers:
    - name: Reload SSHD
      ansible.builtin.service:
        name: sshd
        state: restarted
