---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: statping
  name: statping
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: statping
  type: ClusterIP
