#!/usr/bin/env bash
#MISE description="Run Terraform plan for a workspace"
#USAGE arg "<dir>" help="Terraform workspace" {
#USAGE   choices "cloudflare" "backblaze" "tf-cloud"
#USAGE }
#USAGE arg "[tf-args]" varargs help="Extra args passed to terraform (e.g. -target=x)"

set -euo pipefail

terraform -chdir="${MISE_PROJECT_ROOT}/infra/terraform/${usage_dir?}" plan ${usage_tf_args:-}
