---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    interval: 2m
    # logLevel: debug
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: cloudflare-token
    extraArgs:
      # - --cloudflare-proxied
      - --annotation-filter=external-dns.home.arpa/enabled in (true)
    policy: sync
    sources:
      - ingress
    txtPrefix: "kyz."
    txtOwnerId: "default"
    domainFilters:
      - "waltr.tech"
    serviceMonitor:
      enabled: true
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
