# Indicates the schema used to decode the contents.
version: v1alpha1
# Enable verbose logging to the console.
debug: false
# Indicates whether to pull the machine config upon every boot.
persist: true
# Provides machine specific configuration options.
machine:
  # Defines the role of the machine within the cluster.
  type: controlplane
  # The `token` is used by a machine to join the PKI of the cluster.
  token: ENC[AES256_GCM,data:YAdC9SlQkBn5lMDVtqT2PTKH/PF1HgU=,iv:+F9NVEKm02I8kuD43As/wZbLA6aBqBKUCtIvGhN2taE=,tag:16IRfh0jQMLCs1zzr+8MAA==,type:str]
  # The root certificate authority of the PKI.
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBbXFWRnd5TExiOEFZUElQVHFNL3FhakFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qSXdOVEkzTWpJeU9UUXpXaGNOTXpJd05USTBNakl5T1RReldqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQVAvODJFYWlaZ1UxOFlOU0JsZTVFUTFNSHVUY0UyVEpkMjZ5ClZRY3pHcENCbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkd3OHdLb3J3NkxnbWR3Uwo3VU9TTTJURjZTSUxNQVVHQXl0bGNBTkJBQk1uL1U0Sy82RGt4eU03Q1NWcUhwRzlXamVhWENtd2RzcllXdVhXCjMrWFk3UGw1ZklUS2tkR2RzbHNnT2QweUpDYitzT1A4SThvRzE3S0tzcWc0Z1FnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: ENC[AES256_GCM,data:KccmbBFmQ6bOf3WGbUIw09LmZbvnQnA98cCMCv+mJKqkK0kfhPhCoCY3ztThepsCgL6OMx+sBnIwGy9y4sCRIhsPtMggn3I6GX8htWMjSsWfjtHU3U0D4+bPwiwY6OG4oOoMZ5hH8Ts1fG2GpnOMCKnJH3dKFmXrO2sD9WhuciV649w/oQ2YSqAYQO+sJmwRm9WzDMveHvWtRNDLcfuJo+4kyoOt9u94/zhPRfd8Mt68fnWS,iv:QxCQ1fE/cvtWJKTa4itb3WWRcDZbUtM1MiZKL08a/BE=,tag:2rDWsS+JOwVee/xNGyhR1A==,type:str]
  # Extra certificate subject alternative names for the machine's certificate.
  certSANs:
    - k8s.kyz.waltr.tech
  # Used to provide additional options to the kubelet.
  kubelet:
    # The `image` field is an optional reference to an alternative kubelet image.
    image: ghcr.io/siderolabs/kubelet:v1.23.6
  # Provides machine specific network configuration options.
  network:
    interfaces:
      - interface: eth0
        addresses:
          - 10.10.0.9/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.10.0.1
        mtu: 1500
    nameservers:
      - 192.168.1.1
      - 1.1.1.1
  # Used to provide instructions for installations.
  install:
    # The disk used for installations.
    disk: /dev/sda
    # Allows for supplying the image used to perform the installation.
    image: ghcr.io/siderolabs/installer:v1.0.5
    # Indicates if a bootloader should be installed.
    bootloader: true
    # Indicates if the installation disk should be wiped at installation time.
    wipe: false
  # Features describe individual Talos features that can be switched on or off.
  features:
    # Enable role-based access control (RBAC).
    rbac: true
# Provides cluster specific configuration options.
cluster:
  # Globally unique identifier for this cluster (base64 encoded random 32 bytes).
  id: rrYPKht4ftNnrnmdez4N_iOeYr6vUeJrdcudV9FoVNc=
  # Shared secret of cluster (base64 encoded random 32 bytes).
  secret: ENC[AES256_GCM,data:jHXhjqiRIDaba21oJne6DzDRJ/+gPrNNO6INN+fEZ66G+j9+pBvVBVIRUdE=,iv:lZlJgTUvQSKjvct/Lnm6GZ7wOg5RiI/TG5V7pkqgBlQ=,tag:xA7GJ97IavBYTzJkLbk4zA==,type:str]
  # Provides control plane specific configuration options.
  allowSchedulingOnMasters: true
  controlPlane:
    # Endpoint is the canonical controlplane endpoint, which can be an IP address or a DNS hostname.
    endpoint: https://10.10.0.9:6443
  # Configures the cluster's name.
  clusterName: kyz
  network:
    cni:
      name: none
    # Provides cluster specific network configuration options.
    # The domain used by Kubernetes DNS.
    dnsDomain: cluster.local
    # The pod subnet CIDR.
    podSubnets:
      - 10.244.0.0/16
    # The service subnet CIDR.
    serviceSubnets:
      - 10.96.0.0/12
  # The [bootstrap token](https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/) used to join the cluster.
  token: ENC[AES256_GCM,data:FvluPfM9iy/oJh3JuqO4TspyFK8rImU=,iv:ZPjv1QLVnpqsW/Kj+h9VWC881RzsHlPqnAVLTJ2D6dk=,tag:4tW+u+Q3Fck3zGsl1KFPPQ==,type:str]
  # The key used for the [encryption of secret data at rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/).
  aescbcEncryptionSecret: ENC[AES256_GCM,data:OKTJzOcQS7vV+7jZaZN0zQQh/LbBWrne3Mq/F6Jx2RjXzWXDdJQdxaebS70=,iv:QfK1u0uzKjU2LPA8JRjPyoxgTokl02uqlplQTjHYodU=,tag:lYfSHXpAvXTAcjn/zCMfqQ==,type:str]
  # The base64 encoded root certificate authority used by Kubernetes.
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQVMrZ0F3SUJBZ0lRT25FZmlDR0pMY3ZDaHZjSFJxcFJuekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSXlNRFV5TnpJeU1qazBNMW9YRFRNeU1EVXlOREl5TWprMApNMW93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCSzJOMmZkbEphM0JtM3IyZ0ZGTUREY09QK0lkS3FlRGxRc1Z2THhQeDk0WWJoaVd4U2tFeEUwRUZwRFcKWm1XRWh2ZElkdmI1Qmxkc04xOUN4Z0x0SVFtallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVV6d1c5NjluYUxCS3h3c3EyNTY2eXl1a091bUl3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnYUNHWGswTW0KL2VFK1pveHJsOEF4VXYvb2U0dW5PVGxSSlN5Z1grejB3ZzBDSUQzdG1lSjFJS2VJOTRpUzgvWmRCaGZVT013WApHSWZScXB0a0xZT0FtUW9ECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    key: ENC[AES256_GCM,data:tA6Jfyp8c++7i4HTSUJA9a8PnH21ml5a6OWlTZCOIKBuWFFcVcg45ev1gJoA6dLGF226YDKe+8qdUFtVi/iq70zNM7fnv4nihUb460cC/BK45oQ+kIr2hM/vOHAS/ttLeyyxOnwxbBZuwX+lQDa/jBIgKVGyjBEkCCu16pGrZNTY6z+DEhWFSm65dg1+HbYjGRNl8cbzptQrlg6qsJkVInk0SLBQ6BETIvqetFgi2IfyELGFKHHP4EQD1ockXR1V7bznxEu/noL3vlp9G2NaNAgN9KXmY5jmkvN7fHmOrfyjr8JecCpZp14QxtR+twlXrFy54imjL3FdECnOonBB2NcGDsFWc2w7UWikYiRtNxFSYcKqDlwwz5EM5Kmao8BxZIf+esO0K+E7x7vtVzfx7w==,iv:97JzxzqtjLgBNoM8e5PQF8x4pX9gHrTT99zTKaBZB8E=,tag:UBca5cGWiP/5wFyUiKVkUQ==,type:str]
  # The base64 encoded aggregator certificate authority used by Kubernetes for front-proxy certificate generation.
  aggregatorCA:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJZRENDQVFXZ0F3SUJBZ0lRTzE3NnRxN1ZOdUZJK05iV3R4Z2p4ekFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJeU1EVXlOekl5TWprME0xb1hEVE15TURVeU5ESXlNamswTTFvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCSFJYTEFkZ1A3NjJWbkM2b3c2TmdTdllLbng0UkNWb3F2a0luQlJhUXF6U1krR205c2R4Ck1lVU5XS3BHaEk3YnZzRWU2SHRHV0VoS3ZwMEgwZDI1RHZXallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVVucXFndW03VllHSHZRUEdLYlNaSmhpS2RRdWN3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loCkFKMHpNT3o0TURvbGY1REdOM2hIK2FzaHp2TVJ5Q2FEbVIyd3RXZ1c3TWNVQWlFQTU3VjlqNVhnTEFoOGdUMU8KTndTSGI4ZHlXY1d1VkNQWDU0VVVrOVpObmpzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: ENC[AES256_GCM,data:EgXtrePHTyIvwftbUuT66aere7/zT4+cRupKazvn+mqzc6dpNn4lQIOxi22s7Bn3Z2A0wavoS7WfwJT9tSr7V+rtGZKWi+6CV6cxQ7cttj6QJqYmRl8l1xljS39IdufNWeSgdr0LucXwoEmPeKttclixmqMZR0YNz8RFzZqtvFOr1+9LVqmZqlrKWl7gR4OLptyVMnUGZ8Xl876HkhiRP0CT7a5Uqt5JWastySyjUqz9q2nnNBWM5ClKVNCDHdmRaQBSeuBcngIUmGOs7XIccJgB2Nq7okdr0mx3SZalSO5MiKGb6FyjpWpyX8yo/V4eIZBykqxxstB+rHWBrYjqF+svenJJjNdhCJ0jeY4BJX6yDwQygwHtP83AOE+vXM/y5Q4PrImyziIlSJFB0eXctg==,iv:mtFkgv/BxCA75sq/X3GQh0u+9JXiLgu+p8QMc0IM6Zg=,tag:qhjJskVkTwlJ8BPMZiEpmw==,type:str]
  # The base64 encoded private key for service account token generation.
  serviceAccount:
    key: ENC[AES256_GCM,data:+FHZcxnsfQZyrEQbG20ZOgS3qfNLqetfz64kBTUc5Bk6/0E0AifV7QGT4bUmw2QGzZXgfLJxL9AAWmzu61TrEXUDHcSTzsHS/XtOMee8XdgeU9DMTIqsUDa8FtShzkfVevFJWA90Yhbm5iOgtbpPOh7IVWPWi0ASarRJ/aKZEHYtmxwL7HLJlTSX+GqjaWPLVPfFpNU98SXMHEzT1e/NAxP+dMnM7Gto5XTRNZtyRQVkqaxjVXF7bgO+vAleV2F02nlMEzJu0R67TUPuiq7CVvFOY/71a6NvN49Fwaz3lDdeGFPz2EOG2Xv+Emk7R6igdVXD6zeaupy8d8DiWe8JETi/vWcyMhPf8jg4jm8bjEn2l2GoL2RjCAVeuEJIjCuh4CTu4/mnMzVdHVNdmfKfig==,iv:PJ7kfnAzHajcJZacr0M5uWp5tHGgfjpvCi1/MDw69ic=,tag:RtxYrz0X1AYs6ADYlNAltw==,type:str]
  # API server specific configuration options.
  apiServer:
    # The container image used in the API server manifest.
    image: k8s.gcr.io/kube-apiserver:v1.23.6
    # Extra certificate subject alternative names for the API server's certificate.
    certSANs:
      - 10.10.0.9
      - k8s.kyz.waltr.tech
    # Disable PodSecurityPolicy in the API server and default manifests.
    disablePodSecurityPolicy: true
  # Controller manager server specific configuration options.
  controllerManager:
    # The container image used in the controller manager manifest.
    image: k8s.gcr.io/kube-controller-manager:v1.23.6
  # Kube-proxy server-specific configuration options
  proxy:
    # The container image used in the kube-proxy manifest.
    image: k8s.gcr.io/kube-proxy:v1.23.6
  # Scheduler server specific configuration options.
  scheduler:
    # The container image used in the scheduler manifest.
    image: k8s.gcr.io/kube-scheduler:v1.23.6
  # Configures cluster member discovery.
  discovery:
    # Enable the cluster membership discovery feature.
    enabled: true
    # Configure registries used for cluster member discovery.
    registries:
      # Kubernetes registry uses Kubernetes API server to discover cluster members and stores additional information
      kubernetes: {}
      # Service registry is using an external service to push and pull information about cluster members.
      service: {}
  # Etcd specific configuration options.
  etcd:
    # The `ca` is the root certificate authority of the PKI.
    ca:
      crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmVENDQVNTZ0F3SUJBZ0lSQUk1WCtkL1ZRUmNyMUx6TkdpTXBSWHd3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TWpBMU1qY3lNakk1TkROYUZ3MHpNakExTWpReU1qSTVORE5hTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSNElDQXlWT0hCCjQ1ZnNwOVhqbDVZb3NsajlDZW1vUWE5UUtJV2pucVh5ZjRiSWU2WmdBcWRIeWFTTjMrcTVRODF1aVovcSt5RVkKYzRtcFN3cHFqSDA3bzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkRDK2NPbjEyZWg1CnNweStKMjl4ZTFyeU9XdjVNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJRXR1emNvbTRIS0NpTHlKSVNGeFNId0UKNVNkNGNOYnFxUmlmZzZqL1hUYTFBaUJ5ZXIveTg4WHVWS3lYK1VzbjRSWWRJblJrWWh0bWNmcGJhZTQwaURHSApKZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      key: ENC[AES256_GCM,data:UHbNj7VmWcTL6tkZF28fMeAlmhsPlmhqzWFCm1V1dFIw3y0lrKNXW/jGw9adow1AJXPXe17a7NQPryYPWDejsjp/yyg6UvuEIZG+XJdIPWBf/pgYcoF07N3GQ2fWMcSNB9yvXoUEuyTeapG6pnXWm9PpOcmESnWI3pwhqMc4yjgT6ew6111NWGKicS7y4hfoSRipXU189wjUNS5PuKUFxlb39wM0E1iMPI+a6IjiWjv1zXvmjfxR+ZotYKzbkgQSV9/e7xs1pYMAGW3wDmUVIE4zCO0+vwK3KRzloTTb+Ts33p+ht1zlGtN+i5f66KbpMbW8oI3OwSMLeBBwrwtAxSWZMcFPhZHr6T/xTE44pX9nUHbhAOIYk5iu6R8iX/OoRFJhloV45w8V12Mg4/UDBA==,iv:oKBXFYqoFM2FM3K+F6XQWSDvuOIOc2+Jh/jF1PgWLX0=,tag:xOqF51E7WTWgnOt0cYe0mQ==,type:str]
  # A list of urls that point to additional manifests.
  extraManifests: []
  # A list of inline Kubernetes manifests.
  inlineManifests: []
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age189npag0lz2hl425ldurk8czrpyv69tg4cgqgzl7wjh60w39sysesazu4u6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa0tyUE1BNTFUYXlycWlh
        Mmx6SFFDcnMyZWJoVVp5bTFlRUNDOEJDVm04CkJPSzZUY1B5a3QzZFZvSzFwNGxV
        Uk9TcGpMcjVKTjF2MlFKenowSndjZVEKLS0tIGRDdHdqK3ZMRDZwalBxbXM1bkdL
        SWJ5S3lsNUpSUTZQa3l6VjcxL0Y2M0UK2ZRs3LAop3LP3sgUvG6cjaGziD9H4gF3
        2+fEqu7c991k5JOKLCXqONS2BV+GkOnU4QydvIYAQpjeeH0+icVwKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-05-27T23:21:27Z"
  mac: ENC[AES256_GCM,data:3updaaDOGNg4q9H94laLkDdyTP5c1gtxJ8ZVBw0gKpEsswN46QrljpEuVGJ/qBlGJfVSD2hiiswksAeMuEQ+ZZjsupCloHo8aFz0RWvOnP038QNLsHgVSrToHbrdHQFzHHDcM51D/uAd+r98nUs0qBz3wxl0jW5UbluMPfaBIFY=,iv:6JkSIaFAGhWxVK7GLx50B4i0AOb0GV9auu89RnCsIoc=,tag:+wQX+9mCczjPxOgeEo3KCA==,type:str]
  pgp:
    - created_at: "2022-05-27T23:21:26Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQEMA1nCbZ66Iz0yAQf/eNnPM5MAaXEv0DhG7Za8QGfHz0aSeEgidHJmbu0dBwFm
        Rtt6pRPBYwHofpFocQT4OQetro8PXsrMg3V738Q0ZsRv+1HzqX0/u9YnqmaKyqoK
        T4MwwbiZaP816d8FqsxPZvrGNbPBjZs3B2BO/yaWa82eTVTv+FSmnowhHtE7SyHq
        QXMg+CTD/eQtGHMU4idtEhcqex4r6zhIeueKS+FTf43fI/KDE9kfc0QSd6OtSWRd
        0UxmCa/l3iyGlk+T7iwUpD0K434bYL5b5mDdSCc3woRd/1uVcUN4rLl/pf50rnLL
        16CswzPivAut/l5anx7kMgXf3zOCMtbhpApA0JZH39RoAQkCEAkBDlBeBn6exbck
        tnUBZoZN/eN0P7SW4MnCm7eK9tTt3j0GHGxCsHt5XHlggwdvVaDkqV8b5k4rlNeF
        ZrMLk6JklMTDiQ2vUvI8SiykVltxPZT/ngnWb9YbmUKsR2xN4R65UAw=
        =ZeIT
        -----END PGP MESSAGE-----
      fp: 4186BF653F777F6190DAF3C469977470B0541C75
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.7.2
