---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: k8s-gateway
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: exdns-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    domain: "waltr.tech"
