---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:
    image:
      repository: quay.io/oriedge/k8s_gateway
      tag: v0.3.2
      pullPolicy: IfNotPresent

    podAnnotations:
      configmap.reloader.stakater.com/reload: "k8s-gateway-config"

    args: ["-conf", "/etc/coredns/Corefile"]

    configmap:
      config:
        enabled: true
        data:
          Corefile: |
            .:1053 {
              errors
              log
              health {
                lameduck 5s
              }
              ready
              k8s_gateway ${SECRET_PUBLIC_DOMAIN} ${SECRET_PRIVATE_DOMAIN} ${SECRET_EMAIL_DOMAIN} {
                apex k8s-gateway.networking
                resources Ingress Service
                ttl 300
              }
              prometheus 0.0.0.0:9153
              loop
              reload
              loadbalance
            }
    serviceAccount:
      create: true
      name: k8s-gateway

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: "10.22.2.3"
        ports:
          http:
            enabled: false
          dns:
            enabled: true
            port: 53
            targetPort: 1053
            protocol: UDP

    persistence:
      config:
        enabled: true
        type: configMap
        name: k8s-gateway-config
        mountPath: /etc/coredns
        readOnly: true

    probes:
      readiness:
        custom: true
        spec:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
      liveness:
        custom: true
        spec:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
      startup:
        custom: true
        spec:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP

    resources: {}
