apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationCollection
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: rwaltr
  source:
    path: gitops/cluster-init/applicationsets
    repoURL: https://github.com/rwaltr/infra
