apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationset
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: rwaltr
  source:
    path: gitops/cluster-init/applicationset
    repoURL: https://github.com/rwaltr/infra
