---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spaceengineers
  name: spaceengineers
  namespace: obl
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: "27016"
    port: 27016
    protocol: UDP
    targetPort: 27016
  externalIPs:
    - 172.30.0.12
  selector:
    app: spaceengineers
  type: ClusterIP
