---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rustfs-credentials
    template:
      data:
        RUSTFS_ACCESS_KEY: "{{ .RUSTFS_ACCESS_KEY }}"
        RUSTFS_SECRET_KEY: "{{ .RUSTFS_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: kopia
