---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: statping
  name: statping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statping
  strategy: {}
  template:
    metadata:
      labels:
        app: statping
    spec:
      containers:
      - image: statping/statping
        name: statping
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /app
            name: config
        resources:
          limits:
            memory: "1Gi"
            cpu: 1
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: statping-config
