---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage2
  annotations:
    storageclass.kubernetes.io/is-default-class: true
provisioner: nfs.csi.k8s.io
parameters:
  server: "10.10.0.8"
  share: /tank/k8s
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - hard
  - noatime
