---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-config
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
