---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./externalsecret.yaml
  - ./httproute.yaml
  - ./kopia.yaml
configMapGenerator:
  - name: frigate-config
    files:
      - config.yml=./config.yml
  - name: frigate-s6
    files:
      - log-prepare-run=./s6/log-prepare-run
generatorOptions:
  disableNameSuffixHash: true