---
name: YamlLint

on: # yamllint disable-line rule:truthy
  push:
    paths:
      - '**.yaml'
      - '**.yml'
jobs:
  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .github/lint/.yamllint.yaml
