---
name: Lint

on: # yamllint disable-line rule:truthy
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          yamllint_flags: "-c .github/lint/.yamllint.yaml ./gitops"
 markdownlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
